mpc_node:
  ros__parameters:
    # waypoint_file_path_in_package: "/config/wp-2025-03-08-01-27-47_first_complete_loop.csv"
    waypoint_file_path_in_package: "/config/wp_cp.csv"
    is_sim: True
    is_debug: True
    